/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        for (long i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }

        return n > 1;
    }
    public long firstPrimeNumberIn(String n) {
        long result = 0;

        for (int i = 0; i <= n.length() - 10; i++) {
            long candidate = Long.parseLong(n.substring(i, i + 10));
            if (isPrime(candidate)) {
                result = candidate;
                break;
            }
        }

        return result;
    }
}
